name: 'version bump'
on:
  push:
    branches:
      - main
jobs:
  version-bump:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'add,Adds,new,feat'
          major-wording: 'MAJOR,cut-major'
          patch-wording: 'patch,fixes,chore'     # Providing patch-wording will override commits
          # defaulting to a patch bump.
          rc-wording: 'RELEASE,alpha'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'